default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: rails_channel_development
  username: ashar
  password: password
  host: localhost
  port: 5432
  timeout: 10000

development:
  <<: *default

test:
  adapter: postgresql
  encoding: unicode
  database: rails_channel_test

staging:
  <<: *default

production:
  <<: *default

